// <auto-generated />
namespace Geo.Grid.Tainan.OpenGov.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RelActivityDocumentAndVideoUrlCanNullAndAspNetUserKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelActivityDocumentAndVideoUrlCanNullAndAspNetUserKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201504270651453_Rel-Activity-Document-And-VideoUrl-Can-Null-And-AspNetUser-Key"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
