// <auto-generated />
namespace Geo.Grid.Tainan.OpenGov.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_WaitingMail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_WaitingMail));
        
        string IMigrationMetadata.Id
        {
            get { return "201611300852241_Create_WaitingMail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
