// <auto-generated />
namespace Geo.Grid.Tainan.OpenGov.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddQuestions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddQuestions));
        
        string IMigrationMetadata.Id
        {
            get { return "201608300741589_AddQuestions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
