// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("ACTIVITY", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class Activity
    {

        ///<summary>
        /// 活動編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"ACTIVITY_ID", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.ACTIVITY", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Activity ID")]
        public System.Guid ActivityId { get; set; }

        ///<summary>
        /// 論壇編號
        ///</summary>
        [Column(@"FORUM_ID", Order = 2, TypeName = "uniqueidentifier")]
        [Index(@"IX_FORUM_ID", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Forum ID")]
        public System.Guid ForumId { get; set; }

        ///<summary>
        /// 主題
        ///</summary>
        [Column(@"SUBJECT", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Subject")]
        public string Subject { get; set; }

        ///<summary>
        /// 描述
        ///</summary>
        [Column(@"DESCRIPTION", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(2000)]
        [StringLength(2000)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        ///<summary>
        /// 日期與時間
        ///</summary>
        [Column(@"HOLD_DATE", Order = 5, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Hold date")]
        public string HoldDate { get; set; }

        ///<summary>
        /// 地點
        ///</summary>
        [Column(@"LOCATION", Order = 6, TypeName = "nvarchar")]
        [Required]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Location")]
        public string Location { get; set; }

        [Column(@"IS_ENABLED", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        [Column(@"CREATED_BY", Order = 8, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        [Column(@"CREATED_DATE", Order = 9, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        [Column(@"UPDATE_BY", Order = 10, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Update by")]
        public string UpdateBy { get; set; }

        [Column(@"UPDATE_DATE", Order = 11, TypeName = "datetime")]
        [Required]
        [Display(Name = "Update date")]
        public System.DateTime UpdateDate { get; set; }

        ///<summary>
        /// 0: 論壇活動, 1: 工作坊, 2:招募
        ///</summary>
        [Column(@"ACTIVITY_TYPE", Order = 12, TypeName = "int")]
        [Required]
        [Display(Name = "Activity type")]
        public int ActivityType { get; set; }

        public System.Collections.Generic.ICollection<Document> Documents { get; set; }

        public Activity()
        {
            ActivityId = System.Guid.NewGuid();
            ActivityType = 0;
            Documents = new System.Collections.Generic.List<Document>();
        }
    }

}
// </auto-generated>
