// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class AllowanceConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Allowance>
    {
        public AllowanceConfiguration()
            : this("dbo")
        {
        }

        public AllowanceConfiguration(string schema)
        {
            Property(x => x.Age).IsOptional();
            Property(x => x.AgeMin).IsOptional();
            Property(x => x.AgeMax).IsOptional();
            Property(x => x.LiveIn).IsOptional();
            Property(x => x.IsLiveIn).IsOptional();
            Property(x => x.LiveDays).IsOptional();
            Property(x => x.IsLiveDays).IsOptional();
            Property(x => x.Identity1).IsOptional();
            Property(x => x.Identity2).IsOptional();
            Property(x => x.Income).IsOptional();
            Property(x => x.IncomeValue).IsOptional();
            Property(x => x.Movable).IsOptional();
            Property(x => x.MovableValue).IsOptional();
            Property(x => x.Immovable).IsOptional();
            Property(x => x.ImmovableValue).IsOptional();
            Property(x => x.Others).IsOptional();
            Property(x => x.Docs).IsOptional();
            Property(x => x.Receiver).IsOptional();
            Property(x => x.Contact).IsOptional();
            Property(x => x.MoreInfo).IsOptional();
            Property(x => x.SourceId).IsOptional();

        }
    }

}
// </auto-generated>
