// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("AllowanceSource", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class AllowanceSource
    {

        ///<summary>
        /// 公益臺南-資料集來源管理
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"SourceId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_AllowanceSource", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Source ID")]
        public System.Guid SourceId { get; set; }

        ///<summary>
        /// 資料集名稱
        ///</summary>
        [Column(@"Name", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        ///<summary>
        /// 管理組織
        ///</summary>
        [Column(@"Organization", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Organization")]
        public string Organization { get; set; }

        ///<summary>
        /// 網頁連結
        ///</summary>
        [Column(@"WebSite", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Web site")]
        public string WebSite { get; set; }

        ///<summary>
        /// API
        ///</summary>
        [Column(@"ApiUrl", Order = 5, TypeName = "nvarchar")]
        [Required]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Api url")]
        public string ApiUrl { get; set; }

        ///<summary>
        /// 建立人員
        ///</summary>
        [Column(@"CreatedBy", Order = 6, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        ///<summary>
        /// 建立日期
        ///</summary>
        [Column(@"CreatedDate", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        ///<summary>
        /// 最後更新人員
        ///</summary>
        [Column(@"UpdatedBy", Order = 8, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Updated by")]
        public string UpdatedBy { get; set; }

        ///<summary>
        /// 最後更新日期
        ///</summary>
        [Column(@"UpdatedDate", Order = 9, TypeName = "datetime")]
        [Required]
        [Display(Name = "Updated date")]
        public System.DateTime UpdatedDate { get; set; }

        ///<summary>
        /// 是否啟用
        ///</summary>
        [Column(@"IsEnabled", Order = 10, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        ///<summary>
        /// 資料來源的唯一編碼，由ApiUrl取得
        ///</summary>
        [Column(@"ResourceId", Order = 11, TypeName = "uniqueidentifier")]
        [Required]
        [Display(Name = "Resource ID")]
        public System.Guid ResourceId { get; set; }

        public System.Collections.Generic.ICollection<Allowance> Allowances { get; set; }

        public AllowanceSource()
        {
            CreatedDate = System.DateTime.Now;
            UpdatedDate = System.DateTime.Now;
            IsEnabled = true;
            Allowances = new System.Collections.Generic.List<Allowance>();
        }
    }

}
// </auto-generated>
