// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("AnonymousClick", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class AnonymousClick
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"AnonymousId", Order = 1, TypeName = "nvarchar")]
        [Index(@"PK_dbo.AnonymousClick", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Key]
        [Display(Name = "Anonymous ID")]
        public string AnonymousId { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ClickId", Order = 2, TypeName = "nvarchar")]
        [Index(@"PK_dbo.AnonymousClick", 2, IsUnique = true, IsClustered = true)]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Key]
        [Display(Name = "Click ID")]
        public string ClickId { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ClickType", Order = 3, TypeName = "nvarchar")]
        [Index(@"PK_dbo.AnonymousClick", 3, IsUnique = true, IsClustered = true)]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Key]
        [Display(Name = "Click type")]
        public string ClickType { get; set; }

        [Column(@"ForumId", Order = 4, TypeName = "uniqueidentifier")]
        [Index(@"IX_ForumId", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Forum ID")]
        public System.Guid ForumId { get; set; }


        [ForeignKey("ForumId")] public Forum Forum { get; set; }
    }

}
// </auto-generated>
