// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("Card", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class Card
    {

        ///<summary>
        /// 卡片ID
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"CardId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.Card", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Card ID")]
        public System.Guid CardId { get; set; }

        ///<summary>
        /// 單元名稱
        ///</summary>
        [Column(@"Title", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(150)]
        [StringLength(150)]
        [Display(Name = "Title")]
        public string Title { get; set; }

        ///<summary>
        /// 卡片內容HtmlTag
        ///</summary>
        [Column(@"Contents", Order = 3, TypeName = "nvarchar(max)")]
        [Display(Name = "Contents")]
        public string Contents { get; set; }

        ///<summary>
        /// 單元icon的PhotoId
        ///</summary>
        [Column(@"IconId", Order = 4, TypeName = "uniqueidentifier")]
        [Required]
        [Display(Name = "Icon ID")]
        public System.Guid IconId { get; set; }

        ///<summary>
        /// 卡片顏色
        ///</summary>
        [Column(@"Color", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Color")]
        public int Color { get; set; }

        ///<summary>
        /// 相關連結
        ///</summary>
        [Column(@"WebUrl", Order = 6, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Web url")]
        public string WebUrl { get; set; }

        ///<summary>
        /// 排序
        ///</summary>
        [Column(@"Sort", Order = 7, TypeName = "int")]
        [Required]
        [Display(Name = "Sort")]
        public int Sort { get; set; }

        ///<summary>
        /// 卡片類型 0：其它 1：政府資料 2：行程公開 3：警報告示 4：Open1999 5：管線圖資 6：野生台南 7：重大會議 8：公民論壇 9：市政提案
        ///</summary>
        [Column(@"Type", Order = 8, TypeName = "int")]
        [Required]
        [Display(Name = "Type")]
        public int Type { get; set; }

        ///<summary>
        /// 是否啟用
        ///</summary>
        [Column(@"IsEnabled", Order = 9, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        ///<summary>
        /// 建立人員
        ///</summary>
        [Column(@"CreatedBy", Order = 10, TypeName = "nvarchar")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        ///<summary>
        /// 建立日期
        ///</summary>
        [Column(@"CreatedDate", Order = 11, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        ///<summary>
        /// 更新日期
        ///</summary>
        [Column(@"UpdatedBy", Order = 12, TypeName = "nvarchar")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Updated by")]
        public string UpdatedBy { get; set; }

        ///<summary>
        /// 更新人員
        ///</summary>
        [Column(@"UpdatedDate", Order = 13, TypeName = "datetime")]
        [Required]
        [Display(Name = "Updated date")]
        public System.DateTime UpdatedDate { get; set; }

        ///<summary>
        /// 是否可以刪除
        ///</summary>
        [Column(@"IsDelete", Order = 14, TypeName = "bit")]
        [Required]
        [Display(Name = "Is delete")]
        public bool IsDelete { get; set; }

        ///<summary>
        /// 是否公開
        ///</summary>
        [Column(@"IsPublish", Order = 15, TypeName = "bit")]
        [Required]
        [Display(Name = "Is publish")]
        public bool IsPublish { get; set; }

        public Card()
        {
            CardId = System.Guid.NewGuid();
            Color = 1;
            Sort = 0;
            Type = 0;
            IsEnabled = true;
            CreatedDate = System.DateTime.Now;
            UpdatedDate = System.DateTime.Now;
            IsDelete = true;
            IsPublish = true;
        }
    }

}
// </auto-generated>
