// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class CardConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Card>
    {
        public CardConfiguration()
            : this("dbo")
        {
        }

        public CardConfiguration(string schema)
        {
            Property(x => x.Contents).IsOptional();
            Property(x => x.WebUrl).IsOptional();
            Property(x => x.CreatedBy).IsOptional();
            Property(x => x.UpdatedBy).IsOptional();
        }
    }

}
// </auto-generated>
