// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("DataSetHistory", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class DataSetHistory
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"HistoryId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.DataSetHistory", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "History ID")]
        public System.Guid HistoryId { get; set; }

        [Column(@"SetId", Order = 2, TypeName = "uniqueidentifier")]
        [Index(@"IX_SetId", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Set ID")]
        public System.Guid SetId { get; set; }

        ///<summary>
        /// 標題(版號)
        ///</summary>
        [Column(@"Title", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Title")]
        public string Title { get; set; }

        ///<summary>
        /// 使用指南-md
        ///</summary>
        [Column(@"Contents", Order = 4, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Contents")]
        public string Contents { get; set; }

        ///<summary>
        /// 簡介
        ///</summary>
        [Column(@"Info", Order = 5, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Info")]
        public string Info { get; set; }

        ///<summary>
        /// 排序
        ///</summary>
        [Column(@"Sort", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Sort")]
        public int Sort { get; set; }

        ///<summary>
        /// 是否顯示
        ///</summary>
        [Column(@"IsEnabled", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        ///<summary>
        /// 建立時間
        ///</summary>
        [Column(@"CreatedDate", Order = 8, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        ///<summary>
        /// 建立者
        ///</summary>
        [Column(@"CreatedBy", Order = 9, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        ///<summary>
        /// 修改時間
        ///</summary>
        [Column(@"UpdatedDate", Order = 10, TypeName = "datetime")]
        [Required]
        [Display(Name = "Updated date")]
        public System.DateTime UpdatedDate { get; set; }

        ///<summary>
        /// 修改者
        ///</summary>
        [Column(@"UpdatedBy", Order = 11, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Updated by")]
        public string UpdatedBy { get; set; }


        [ForeignKey("SetId")] public DataSet DataSet { get; set; }

        public DataSetHistory()
        {
            HistoryId = System.Guid.NewGuid();
            Title = "";
            Contents = "";
            Info = "";
            Sort = 0;
            IsEnabled = true;
            CreatedDate = System.DateTime.Now;
            CreatedBy = "";
            UpdatedDate = System.DateTime.Now;
            UpdatedBy = "";
        }
    }

}
// </auto-generated>
