// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class DiscussConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Discuss>
    {
        public DiscussConfiguration()
            : this("dbo")
        {
        }

        public DiscussConfiguration(string schema)
        {
            Property(x => x.UpperId).IsOptional();

            HasMany(t => t.Tags).WithMany(t => t.Discusses).Map(m =>
            {
                m.ToTable("REL_DISCUSS_TAG", "dbo");
                m.MapLeftKey("DiscussId");
                m.MapRightKey("TagId");
            });
            HasMany(t => t.AspNetUsers).WithMany(t => t.Discusses_DiscussId).Map(m =>
            {
                m.ToTable("REL_USER_PUSH", "dbo");
                m.MapLeftKey("DiscussId");
                m.MapRightKey("Id");
            });
        }
    }

}
// </auto-generated>
