// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("DistrictOffice", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class DistrictOffice
    {

        ///<summary>
        /// 區公所編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"OfficeId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_DistrictOffice", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Office ID")]
        public System.Guid OfficeId { get; set; }

        ///<summary>
        /// 區公所名稱
        ///</summary>
        [Column(@"Name", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        ///<summary>
        /// 經度
        ///</summary>
        [Column(@"Lng", Order = 3, TypeName = "float")]
        [Required]
        [Display(Name = "Lng")]
        public double Lng { get; set; }

        ///<summary>
        /// 緯度
        ///</summary>
        [Column(@"Lat", Order = 4, TypeName = "float")]
        [Required]
        [Display(Name = "Lat")]
        public double Lat { get; set; }

        public DistrictOffice()
        {
            OfficeId = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
