// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class EngineeringConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Engineering>
    {
        public EngineeringConfiguration()
            : this("dbo")
        {
        }

        public EngineeringConfiguration(string schema)
        {
            Property(x => x.Amount).HasPrecision(20,0);
            Property(x => x.Summary).IsOptional();
            Property(x => x.TargetCompleteDate).IsOptional();
            Property(x => x.ChangeCompleteDate).IsOptional();
            Property(x => x.TargetProgress).HasPrecision(5,2);
            Property(x => x.ActualProgress).HasPrecision(5,2);
            Property(x => x.Discrepancy).HasPrecision(5,2);
            Property(x => x.BehindReason).IsOptional();
            Property(x => x.Analysis).IsOptional();
            Property(x => x.Solution).IsOptional();
            Property(x => x.ImproveTermDate).IsOptional();
            Property(x => x.ActualCompleteDate).IsOptional();
        }
    }

}
// </auto-generated>
