// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("EngineeringLog", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class EngineeringLog
    {

        ///<summary>
        /// 工程標案匯入紀錄編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"LogId", Order = 1, TypeName = "bigint")]
        [Index(@"PK_EngineeringLog", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Log ID")]
        public long LogId { get; set; }

        ///<summary>
        /// 原始資料,CSV檔案格式,不換行(;分隔)
        ///</summary>
        [Column(@"LogMessage", Order = 2, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Log message")]
        public string LogMessage { get; set; }

        ///<summary>
        /// 檔案名稱
        ///</summary>
        [Column(@"FileName", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "File name")]
        public string FileName { get; set; }

        ///<summary>
        /// 建立人員
        ///</summary>
        [Column(@"CreatedBy", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        ///<summary>
        /// 建立日期
        ///</summary>
        [Column(@"CreatedDate", Order = 5, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        ///<summary>
        /// 是否啟用
        ///</summary>
        [Column(@"IsEnabled", Order = 6, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        public EngineeringLog()
        {
            CreatedDate = System.DateTime.Now;
            IsEnabled = true;
        }
    }

}
// </auto-generated>
