// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("FORUM", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class Forum
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"FORUM_ID", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.FORUM", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Forum ID")]
        public System.Guid ForumId { get; set; }

        ///<summary>
        /// 主題類別
        ///</summary>
        [Column(@"CATEGORY", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Category")]
        public string Category { get; set; }

        ///<summary>
        /// 主題
        ///</summary>
        [Column(@"SUBJECT", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Subject")]
        public string Subject { get; set; }

        ///<summary>
        /// 主辦單位
        ///</summary>
        [Column(@"HOLDER", Order = 4, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Holder")]
        public string Holder { get; set; }

        ///<summary>
        /// 描述
        ///</summary>
        [Column(@"DESCRIPTION", Order = 5, TypeName = "nvarchar")]
        [Required]
        [MaxLength(4000)]
        [StringLength(4000)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        ///<summary>
        /// 發佈時間
        ///</summary>
        [Column(@"OPEN_DATE", Order = 6, TypeName = "datetime")]
        [Required]
        [Display(Name = "Open date")]
        public System.DateTime OpenDate { get; set; }

        ///<summary>
        /// 截止時間
        ///</summary>
        [Column(@"CLOSE_DATE", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Close date")]
        public System.DateTime CloseDate { get; set; }

        [Column(@"IS_ENABLED", Order = 8, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        [Column(@"CREATED_BY", Order = 9, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        [Column(@"CREATED_DATE", Order = 10, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        [Column(@"UPDATE_BY", Order = 11, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Update by")]
        public string UpdateBy { get; set; }

        [Column(@"UPDATE_DATE", Order = 12, TypeName = "datetime")]
        [Required]
        [Display(Name = "Update date")]
        public System.DateTime UpdateDate { get; set; }

        [Column(@"FORUM_TYPE", Order = 13, TypeName = "int")]
        [Required]
        [Display(Name = "Forum type")]
        public int ForumType { get; set; }

        [Column(@"UPPER_ID", Order = 14, TypeName = "uniqueidentifier")]
        [Display(Name = "Upper ID")]
        public System.Guid? UpperId { get; set; }

        ///<summary>
        /// 討論區公告
        ///</summary>
        [Column(@"ANNOUNCEMENT", Order = 15, TypeName = "nvarchar")]
        [MaxLength(4000)]
        [StringLength(4000)]
        [Display(Name = "Announcement")]
        public string Announcement { get; set; }

        [Column(@"DataSetUnitId", Order = 16, TypeName = "uniqueidentifier")]
        [Index(@"IX_DataSetUnitId", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Data set unit ID")]
        public System.Guid DataSetUnitId { get; set; }

        public System.Collections.Generic.ICollection<AnonymousClick> AnonymousClicks { get; set; }
        public System.Collections.Generic.ICollection<Discuss> Discusses { get; set; }
        public System.Collections.Generic.ICollection<Document> Documents { get; set; }
        public System.Collections.Generic.ICollection<Hyperlink> Hyperlinks { get; set; }
        public System.Collections.Generic.ICollection<MdQuestInfo> MdQuestInfoes { get; set; }
        public System.Collections.Generic.ICollection<Photo> Photos { get; set; }
        public System.Collections.Generic.ICollection<Tag> Tags { get; set; }
        public System.Collections.Generic.ICollection<Vote> Votes { get; set; }

        public Forum()
        {
            ForumId = System.Guid.NewGuid();
            ForumType = 0;
            AnonymousClicks = new System.Collections.Generic.List<AnonymousClick>();
            Discusses = new System.Collections.Generic.List<Discuss>();
            MdQuestInfoes = new System.Collections.Generic.List<MdQuestInfo>();
            Tags = new System.Collections.Generic.List<Tag>();
            Votes = new System.Collections.Generic.List<Vote>();
            Documents = new System.Collections.Generic.List<Document>();
            Hyperlinks = new System.Collections.Generic.List<Hyperlink>();
            Photos = new System.Collections.Generic.List<Photo>();
        }
    }

}
// </auto-generated>
