// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ForumConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Forum>
    {
        public ForumConfiguration()
            : this("dbo")
        {
        }

        public ForumConfiguration(string schema)
        {
            Property(x => x.Holder).IsOptional();
            Property(x => x.UpperId).IsOptional();
            Property(x => x.Announcement).IsOptional();
            HasMany(t => t.Hyperlinks).WithMany(t => t.Fora).Map(m =>
            {
                m.ToTable("REL_FORUM_HYPERLINK", "dbo");
                m.MapLeftKey("FORUM_ID");
                m.MapRightKey("HYPERLINK_ID");
            });
            HasMany(t => t.Photos).WithMany(t => t.Fora).Map(m =>
            {
                m.ToTable("REL_FORUM_PHOTO", "dbo");
                m.MapLeftKey("FORUM_ID");
                m.MapRightKey("PHOTO_ID");
            });
        }
    }

}
// </auto-generated>
