// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("HYPERLINK", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class Hyperlink
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"HYPERLINK_ID", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.HYPERLINK", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Hyperlink ID")]
        public System.Guid HyperlinkId { get; set; }

        [Column(@"TITLE", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Title")]
        public string Title { get; set; }

        [Column(@"DESCRIPTION", Order = 3, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Column(@"URL", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(200)]
        [StringLength(200)]
        [Url]
        [Display(Name = "Url")]
        public string Url { get; set; }

        [Column(@"IS_ENABLED", Order = 5, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        [Column(@"CREATED_BY", Order = 6, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        [Column(@"CREATED_DATE", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        [Column(@"UPDATE_BY", Order = 8, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Update by")]
        public string UpdateBy { get; set; }

        [Column(@"UPDATE_DATE", Order = 9, TypeName = "datetime")]
        [Required]
        [Display(Name = "Update date")]
        public System.DateTime UpdateDate { get; set; }

        public System.Collections.Generic.ICollection<Forum> Fora { get; set; }

        public Hyperlink()
        {
            HyperlinkId = System.Guid.NewGuid();
            Fora = new System.Collections.Generic.List<Forum>();
        }
    }

}
// </auto-generated>
