// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    public interface IOpenGovContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Activity> Activities { get; set; }
        System.Data.Entity.DbSet<Allowance> Allowances { get; set; }
        System.Data.Entity.DbSet<AllowanceSource> AllowanceSources { get; set; }
        System.Data.Entity.DbSet<AnonymousClick> AnonymousClicks { get; set; }
        System.Data.Entity.DbSet<AspNetRole> AspNetRoles { get; set; }
        System.Data.Entity.DbSet<AspNetUser> AspNetUsers { get; set; }
        System.Data.Entity.DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        System.Data.Entity.DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        System.Data.Entity.DbSet<Banner> Banners { get; set; }
        System.Data.Entity.DbSet<Card> Cards { get; set; }
        System.Data.Entity.DbSet<CityTown> CityTowns { get; set; }
        System.Data.Entity.DbSet<DataSet> DataSets { get; set; }
        System.Data.Entity.DbSet<DataSetExtension> DataSetExtensions { get; set; }
        System.Data.Entity.DbSet<DataSetHistory> DataSetHistories { get; set; }
        System.Data.Entity.DbSet<DataSetType> DataSetTypes { get; set; }
        System.Data.Entity.DbSet<DataSetUnit> DataSetUnits { get; set; }
        System.Data.Entity.DbSet<Discuss> Discusses { get; set; }
        System.Data.Entity.DbSet<DistrictOffice> DistrictOffices { get; set; }
        System.Data.Entity.DbSet<Document> Documents { get; set; }
        System.Data.Entity.DbSet<DocumentExt> DocumentExts { get; set; }
        System.Data.Entity.DbSet<Engineering> Engineerings { get; set; }
        System.Data.Entity.DbSet<EngineeringLog> EngineeringLogs { get; set; }
        System.Data.Entity.DbSet<Forum> Fora { get; set; }
        System.Data.Entity.DbSet<Hyperlink> Hyperlinks { get; set; }
        System.Data.Entity.DbSet<MdCheck> MdChecks { get; set; }
        System.Data.Entity.DbSet<MdFillQuest> MdFillQuests { get; set; }
        System.Data.Entity.DbSet<MdQuestInfo> MdQuestInfoes { get; set; }
        System.Data.Entity.DbSet<MdQuestion> MdQuestions { get; set; }
        System.Data.Entity.DbSet<MdQuestionGroup> MdQuestionGroups { get; set; }
        System.Data.Entity.DbSet<MdQuestNecessaryRel> MdQuestNecessaryRels { get; set; }
        System.Data.Entity.DbSet<MdQuestSetItem> MdQuestSetItems { get; set; }
        System.Data.Entity.DbSet<Menu> Menus { get; set; }
        System.Data.Entity.DbSet<Nlog> Nlogs { get; set; }
        System.Data.Entity.DbSet<Participation> Participations { get; set; }
        System.Data.Entity.DbSet<ParticipationActivity> ParticipationActivities { get; set; }
        System.Data.Entity.DbSet<ParticipationAnonymousClick> ParticipationAnonymousClicks { get; set; }
        System.Data.Entity.DbSet<ParticipationDiscuss> ParticipationDiscusses { get; set; }
        System.Data.Entity.DbSet<ParticipationDocument> ParticipationDocuments { get; set; }
        System.Data.Entity.DbSet<ParticipationDocumentExt> ParticipationDocumentExts { get; set; }
        System.Data.Entity.DbSet<ParticipationHyperlink> ParticipationHyperlinks { get; set; }
        System.Data.Entity.DbSet<ParticipationTag> ParticipationTags { get; set; }
        System.Data.Entity.DbSet<Photo> Photos { get; set; }
        System.Data.Entity.DbSet<PhotoExt> PhotoExts { get; set; }
        System.Data.Entity.DbSet<ShowCase> ShowCases { get; set; }
        System.Data.Entity.DbSet<ShowCaseUrl> ShowCaseUrls { get; set; }
        System.Data.Entity.DbSet<Tag> Tags { get; set; }
        System.Data.Entity.DbSet<ViewQuestionExport> ViewQuestionExports { get; set; }
        System.Data.Entity.DbSet<Vote> Votes { get; set; }
        System.Data.Entity.DbSet<VoteBasic> VoteBasics { get; set; }
        System.Data.Entity.DbSet<VoteBasicGroup> VoteBasicGroups { get; set; }
        System.Data.Entity.DbSet<VoteCheck> VoteChecks { get; set; }
        System.Data.Entity.DbSet<VoteFillBasic> VoteFillBasics { get; set; }
        System.Data.Entity.DbSet<VoteFillOption> VoteFillOptions { get; set; }
        System.Data.Entity.DbSet<VoteOption> VoteOptions { get; set; }
        System.Data.Entity.DbSet<WaitingMail> WaitingMails { get; set; }
        System.Data.Entity.DbSet<Youtube> Youtubes { get; set; }

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
