// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("MdFillQuest", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class MdFillQuest
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"FillId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.MdFillQuest", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Fill ID")]
        public System.Guid FillId { get; set; }

        [Column(@"InfoId", Order = 2, TypeName = "uniqueidentifier")]
        [Required]
        [Display(Name = "Info ID")]
        public System.Guid InfoId { get; set; }

        [Column(@"MdFillUserId", Order = 3, TypeName = "uniqueidentifier")]
        [Required]
        [Display(Name = "Md fill user ID")]
        public System.Guid MdFillUserId { get; set; }

        [Column(@"QstId", Order = 4, TypeName = "uniqueidentifier")]
        [Index(@"IX_QstId", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Qst ID")]
        public System.Guid QstId { get; set; }

        [Column(@"SetId", Order = 5, TypeName = "uniqueidentifier")]
        [Required]
        [Display(Name = "Set ID")]
        public System.Guid SetId { get; set; }

        [Column(@"FillDesc", Order = 6, TypeName = "nvarchar")]
        [MaxLength(3000)]
        [StringLength(3000)]
        [Display(Name = "Fill desc")]
        public string FillDesc { get; set; }

        [Column(@"FillScore", Order = 7, TypeName = "int")]
        [Required]
        [Display(Name = "Fill score")]
        public int FillScore { get; set; }

        [Column(@"EditDate", Order = 8, TypeName = "datetime")]
        [Required]
        [Display(Name = "Edit date")]
        public System.DateTime EditDate { get; set; }

        [Column(@"Editer", Order = 9, TypeName = "uniqueidentifier")]
        [Display(Name = "Editer")]
        public System.Guid? Editer { get; set; }

        ///<summary>
        /// 是否顯示
        ///</summary>
        [Column(@"IsEnable", Order = 10, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enable")]
        public bool IsEnable { get; set; }

        ///<summary>
        /// 填寫人eMail
        ///</summary>
        [Column(@"MdFillUserEmail", Order = 11, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Md fill user email")]
        public string MdFillUserEmail { get; set; }


        [ForeignKey("QstId")] public MdQuestion MdQuestion { get; set; }

        public MdFillQuest()
        {
            IsEnable = true;
            MdFillUserEmail = "";
        }
    }

}
// </auto-generated>
