// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("MdQuestionGroup", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class MdQuestionGroup
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"GroupId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.MdQuestionGroup", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Group ID")]
        public System.Guid GroupId { get; set; }

        [Column(@"GroupTitle", Order = 2, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Group title")]
        public string GroupTitle { get; set; }

        [Column(@"InfoId", Order = 3, TypeName = "uniqueidentifier")]
        [Index(@"IX_InfoId", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Info ID")]
        public System.Guid InfoId { get; set; }

        [Column(@"GroupDesc", Order = 4, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Group desc")]
        public string GroupDesc { get; set; }

        [Column(@"GroupSort", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Group sort")]
        public int GroupSort { get; set; }

        [Column(@"IsEnable", Order = 6, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enable")]
        public bool IsEnable { get; set; }

        [Column(@"EditDate", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Edit date")]
        public System.DateTime EditDate { get; set; }

        [Column(@"Editer", Order = 8, TypeName = "uniqueidentifier")]
        [Display(Name = "Editer")]
        public System.Guid? Editer { get; set; }

        public System.Collections.Generic.ICollection<MdQuestion> MdQuestions { get; set; }


        [ForeignKey("InfoId")] public MdQuestInfo MdQuestInfo { get; set; }

        public MdQuestionGroup()
        {
            MdQuestions = new System.Collections.Generic.List<MdQuestion>();
        }
    }

}
// </auto-generated>
