// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("MdQuestion", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class MdQuestion
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"QstId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.MdQuestion", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Qst ID")]
        public System.Guid QstId { get; set; }

        [Column(@"GroupId", Order = 2, TypeName = "uniqueidentifier")]
        [Index(@"IX_GroupId", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Group ID")]
        public System.Guid GroupId { get; set; }

        [Column(@"QstSorting", Order = 3, TypeName = "int")]
        [Required]
        [Display(Name = "Qst sorting")]
        public int QstSorting { get; set; }

        [Column(@"QstAnsType", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Qst ans type")]
        public int QstAnsType { get; set; }

        [Column(@"QstQuestion", Order = 5, TypeName = "nvarchar")]
        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Qst question")]
        public string QstQuestion { get; set; }

        [Column(@"QstScore", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Qst score")]
        public int QstScore { get; set; }

        [Column(@"EditDate", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Edit date")]
        public System.DateTime EditDate { get; set; }

        [Column(@"Editer", Order = 8, TypeName = "uniqueidentifier")]
        [Display(Name = "Editer")]
        public System.Guid? Editer { get; set; }

        [Column(@"IsEnable", Order = 9, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enable")]
        public bool IsEnable { get; set; }

        [Column(@"IsRequired", Order = 10, TypeName = "bit")]
        [Required]
        [Display(Name = "Is required")]
        public bool IsRequired { get; set; }

        public System.Collections.Generic.ICollection<MdFillQuest> MdFillQuests { get; set; }
        public System.Collections.Generic.ICollection<MdQuestSetItem> MdQuestSetItems { get; set; }


        [ForeignKey("GroupId")] public MdQuestionGroup MdQuestionGroup { get; set; }

        public MdQuestion()
        {
            MdFillQuests = new System.Collections.Generic.List<MdFillQuest>();
            MdQuestSetItems = new System.Collections.Generic.List<MdQuestSetItem>();
        }
    }

}
// </auto-generated>
