// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("MdQuestInfo", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class MdQuestInfo
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"InfoId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.MdQuestInfo", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Info ID")]
        public System.Guid InfoId { get; set; }

        ///<summary>
        /// 問卷標題
        ///</summary>
        [Column(@"InfoTitle", Order = 2, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Info title")]
        public string InfoTitle { get; set; }

        ///<summary>
        /// 問卷描述
        ///</summary>
        [Column(@"InfoDesc", Order = 3, TypeName = "nvarchar")]
        [MaxLength(3000)]
        [StringLength(3000)]
        [Display(Name = "Info desc")]
        public string InfoDesc { get; set; }

        ///<summary>
        /// 開放填寫日期(起)
        ///</summary>
        [Column(@"InfoDateSt", Order = 4, TypeName = "datetime")]
        [Display(Name = "Info date st")]
        public System.DateTime? InfoDateSt { get; set; }

        ///<summary>
        /// 開放填寫日期(迄)
        ///</summary>
        [Column(@"InfoDateEnd", Order = 5, TypeName = "datetime")]
        [Display(Name = "Info date end")]
        public System.DateTime? InfoDateEnd { get; set; }

        ///<summary>
        /// 是否開放 1:使用  0:停用
        ///</summary>
        [Column(@"InfoValid", Order = 6, TypeName = "bit")]
        [Required]
        [Display(Name = "Info valid")]
        public bool InfoValid { get; set; }

        ///<summary>
        /// 問卷結語
        ///</summary>
        [Column(@"InfoFooter", Order = 7, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Info footer")]
        public string InfoFooter { get; set; }

        ///<summary>
        /// 更新時間
        ///</summary>
        [Column(@"EditDate", Order = 8, TypeName = "datetime")]
        [Required]
        [Display(Name = "Edit date")]
        public System.DateTime EditDate { get; set; }

        ///<summary>
        /// 使用者編號
        ///</summary>
        [Column(@"Editer", Order = 9, TypeName = "uniqueidentifier")]
        [Display(Name = "Editer")]
        public System.Guid? Editer { get; set; }

        ///<summary>
        /// 0刪除 1存在
        ///</summary>
        [Column(@"IsEnable", Order = 10, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enable")]
        public bool IsEnable { get; set; }

        ///<summary>
        /// 所屬的開放論壇ID
        ///</summary>
        [Column(@"ForumId", Order = 11, TypeName = "uniqueidentifier")]
        [Index(@"IX_ForumId", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Forum ID")]
        public System.Guid ForumId { get; set; }

        ///<summary>
        /// 1:無登入、無驗證；2:無登入，需email驗證；3:需登入，無email驗證
        ///</summary>
        [Column(@"VerifyType", Order = 12, TypeName = "int")]
        [Required]
        [Display(Name = "Verify type")]
        public int VerifyType { get; set; }

        ///<summary>
        /// 問卷結果是否開放(統計表)
        ///</summary>
        [Column(@"IsGather", Order = 13, TypeName = "bit")]
        [Required]
        [Display(Name = "Is gather")]
        public bool IsGather { get; set; }

        public System.Collections.Generic.ICollection<MdQuestionGroup> MdQuestionGroups { get; set; }


        [ForeignKey("ForumId")] public Forum Forum { get; set; }

        public MdQuestInfo()
        {
            IsEnable = true;
            VerifyType = 0;
            IsGather = false;
            MdQuestionGroups = new System.Collections.Generic.List<MdQuestionGroup>();
        }
    }

}
// </auto-generated>
