// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class MdQuestInfoConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MdQuestInfo>
    {
        public MdQuestInfoConfiguration()
            : this("dbo")
        {
        }

        public MdQuestInfoConfiguration(string schema)
        {
            Property(x => x.InfoTitle).IsOptional();
            Property(x => x.InfoDesc).IsOptional();
            Property(x => x.InfoDateSt).IsOptional();
            Property(x => x.InfoDateEnd).IsOptional();
            Property(x => x.InfoFooter).IsOptional();
            Property(x => x.Editer).IsOptional();

        }
    }

}
// </auto-generated>
