// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("MdQuestSetItem", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class MdQuestSetItem
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"SetId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.MdQuestSetItem", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Set ID")]
        public System.Guid SetId { get; set; }

        [Column(@"QstId", Order = 2, TypeName = "uniqueidentifier")]
        [Index(@"IX_QstId", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Qst ID")]
        public System.Guid QstId { get; set; }

        [Column(@"SetDesc", Order = 3, TypeName = "nvarchar")]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Set desc")]
        public string SetDesc { get; set; }

        [Column(@"SetScore", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Set score")]
        public int SetScore { get; set; }

        [Column(@"SetSorting", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Set sorting")]
        public int SetSorting { get; set; }

        [Column(@"SetNote", Order = 6, TypeName = "bit")]
        [Required]
        [Display(Name = "Set note")]
        public bool SetNote { get; set; }

        [Column(@"EditDate", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Edit date")]
        public System.DateTime EditDate { get; set; }

        [Column(@"Editer", Order = 8, TypeName = "uniqueidentifier")]
        [Display(Name = "Editer")]
        public System.Guid? Editer { get; set; }

        [Column(@"IsEnable", Order = 9, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enable")]
        public bool IsEnable { get; set; }

        public MdQuestNecessaryRel MdQuestNecessaryRel { get; set; }


        [ForeignKey("QstId")] public MdQuestion MdQuestion { get; set; }
    }

}
// </auto-generated>
