// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("Menu", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class Menu
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"MenuId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.Menu", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Menu ID")]
        public System.Guid MenuId { get; set; }

        [Column(@"Name", Order = 2, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Column(@"Controller", Order = 3, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Controller")]
        public string Controller { get; set; }

        [Column(@"Action", Order = 4, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Action")]
        public string Action { get; set; }

        [Column(@"Area", Order = 5, TypeName = "nvarchar(max)")]
        [Display(Name = "Area")]
        public string Area { get; set; }

        [Column(@"Sort", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Sort")]
        public int Sort { get; set; }

        [Column(@"IsEnabled", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        [Column(@"CreatedBy", Order = 8, TypeName = "nvarchar")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        [Column(@"CreatedDate", Order = 9, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        [Column(@"UpdatedBy", Order = 10, TypeName = "nvarchar")]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Updated by")]
        public string UpdatedBy { get; set; }

        [Column(@"UpdatedDate", Order = 11, TypeName = "datetime")]
        [Required]
        [Display(Name = "Updated date")]
        public System.DateTime UpdatedDate { get; set; }

        public System.Collections.Generic.ICollection<AspNetRole> AspNetRoles { get; set; }

        public Menu()
        {
            MenuId = System.Guid.NewGuid();
            AspNetRoles = new System.Collections.Generic.List<AspNetRole>();
        }
    }

}
// </auto-generated>
