// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class NlogConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Nlog>
    {
        public NlogConfiguration()
            : this("dbo")
        {
        }

        public NlogConfiguration(string schema)
        {
            Property(x => x.UserName).IsOptional();
            Property(x => x.ServerName).IsOptional();
            Property(x => x.Port).IsOptional();
            Property(x => x.Url).IsOptional();
            Property(x => x.Https).IsOptional();
            Property(x => x.ServerAddress).IsOptional();
            Property(x => x.RemoteAddress).IsOptional();
            Property(x => x.Logger).IsOptional();
            Property(x => x.Callsite).IsOptional();
            Property(x => x.Exception).IsOptional();
        }
    }

}
// </auto-generated>
