// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("ParticipationDocumentExt", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ParticipationDocumentExt
    {

        ///<summary>
        /// 附件編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"DocumentId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_ParticipationDocumentExt", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Document ID")]
        [ForeignKey("ParticipationDocument")]
        public System.Guid DocumentId { get; set; }

        ///<summary>
        /// 檔案內容
        ///</summary>
        [Column(@"Original", Order = 2, TypeName = "varbinary(max)")]
        [Required]
        [Display(Name = "Original")]
        public byte[] Original { get; set; }


        [ForeignKey("DocumentId")] public ParticipationDocument ParticipationDocument { get; set; }
    }

}
// </auto-generated>
