// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ParticipationDocumentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ParticipationDocument>
    {
        public ParticipationDocumentConfiguration()
            : this("dbo")
        {
        }

        public ParticipationDocumentConfiguration(string schema)
        {
            Property(x => x.Alt).IsOptional();
            HasMany(t => t.Participations).WithMany(t => t.ParticipationDocuments).Map(m =>
            {
                m.ToTable("RelParticipationDocument", "dbo");
                m.MapLeftKey("DocumentId");
                m.MapRightKey("ParticipationId");
            });
        }
    }

}
// </auto-generated>
