// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("ParticipationDocument", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ParticipationDocument
    {

        ///<summary>
        /// 附件編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"DocumentId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_ParticipationDocument", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Document ID")]
        public System.Guid DocumentId { get; set; }

        ///<summary>
        /// 附件檔案大小
        ///</summary>
        [Column(@"Size", Order = 2, TypeName = "bigint")]
        [Required]
        [Display(Name = "Size")]
        public long Size { get; set; }

        ///<summary>
        /// 附件檔名
        ///</summary>
        [Column(@"FileName", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "File name")]
        public string FileName { get; set; }

        ///<summary>
        /// 附件類型
        ///</summary>
        [Column(@"FileType", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "File type")]
        public string FileType { get; set; }

        ///<summary>
        /// 附件內容說明
        ///</summary>
        [Column(@"Alt", Order = 5, TypeName = "nvarchar")]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Alt")]
        public string Alt { get; set; }

        ///<summary>
        /// 附件類別, 0:一般文件, 1:市府回應
        ///</summary>
        [Column(@"DocumentType", Order = 6, TypeName = "int")]
        [Required]
        [Display(Name = "Document type")]
        public int DocumentType { get; set; }

        ///<summary>
        /// 是否顯示
        ///</summary>
        [Column(@"IsEnabled", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        ///<summary>
        /// 建立人員
        ///</summary>
        [Column(@"CreatedBy", Order = 8, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        ///<summary>
        /// 建立時間
        ///</summary>
        [Column(@"CreatedDate", Order = 9, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        ///<summary>
        /// 修改人員
        ///</summary>
        [Column(@"UpdatedBy", Order = 10, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Updated by")]
        public string UpdatedBy { get; set; }

        ///<summary>
        /// 修改時間
        ///</summary>
        [Column(@"UpdatedDate", Order = 11, TypeName = "datetime")]
        [Required]
        [Display(Name = "Updated date")]
        public System.DateTime UpdatedDate { get; set; }

        public ParticipationDocumentExt ParticipationDocumentExt { get; set; }
        public System.Collections.Generic.ICollection<Participation> Participations { get; set; }
        public System.Collections.Generic.ICollection<ParticipationActivity> ParticipationActivities { get; set; }

        public ParticipationDocument()
        {
            DocumentId = System.Guid.NewGuid();
            DocumentType = 0;
            IsEnabled = true;
            CreatedBy = "";
            CreatedDate = System.DateTime.Now;
            UpdatedBy = "";
            UpdatedDate = System.DateTime.Now;
            ParticipationActivities = new System.Collections.Generic.List<ParticipationActivity>();
            Participations = new System.Collections.Generic.List<Participation>();
        }
    }

}
// </auto-generated>
