// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("Participation", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class Participation
    {

        ///<summary>
        /// 市政參與編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ParticipationId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_Participation", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Participation ID")]
        public System.Guid ParticipationId { get; set; }

        ///<summary>
        /// 主題類別
        ///</summary>
        [Column(@"Category", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Category")]
        public string Category { get; set; }

        ///<summary>
        /// 主辦單位編號
        ///</summary>
        [Column(@"DataSetUnitId", Order = 3, TypeName = "uniqueidentifier")]
        [Required]
        [Display(Name = "Data set unit ID")]
        public System.Guid DataSetUnitId { get; set; }

        ///<summary>
        /// 主題
        ///</summary>
        [Column(@"Subject", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Subject")]
        public string Subject { get; set; }

        ///<summary>
        /// 描述
        ///</summary>
        [Column(@"Description", Order = 5, TypeName = "nvarchar")]
        [Required]
        [MaxLength(4000)]
        [StringLength(4000)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        ///<summary>
        /// 討論區公告
        ///</summary>
        [Column(@"Announcement", Order = 6, TypeName = "nvarchar")]
        [MaxLength(4000)]
        [StringLength(4000)]
        [Display(Name = "Announcement")]
        public string Announcement { get; set; }

        ///<summary>
        /// 是否開放討論區
        ///</summary>
        [Column(@"EnableDiscuss", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Enable discuss")]
        public bool EnableDiscuss { get; set; }

        ///<summary>
        /// 發佈時間
        ///</summary>
        [Column(@"OpenDate", Order = 8, TypeName = "datetime")]
        [Required]
        [Display(Name = "Open date")]
        public System.DateTime OpenDate { get; set; }

        ///<summary>
        /// 截止時間
        ///</summary>
        [Column(@"CloseDate", Order = 9, TypeName = "datetime")]
        [Required]
        [Display(Name = "Close date")]
        public System.DateTime CloseDate { get; set; }

        ///<summary>
        /// 是否封存
        ///</summary>
        [Column(@"IsMothball", Order = 10, TypeName = "bit")]
        [Required]
        [Display(Name = "Is mothball")]
        public bool IsMothball { get; set; }

        ///<summary>
        /// 是否顯示
        ///</summary>
        [Column(@"IsEnabled", Order = 11, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        ///<summary>
        /// 建立人員
        ///</summary>
        [Column(@"CreatedBy", Order = 12, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        ///<summary>
        /// 建立時間
        ///</summary>
        [Column(@"CreatedDate", Order = 13, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        ///<summary>
        /// 修改人員
        ///</summary>
        [Column(@"UpdatedBy", Order = 14, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Updated by")]
        public string UpdatedBy { get; set; }

        ///<summary>
        /// 修改時間
        ///</summary>
        [Column(@"UpdatedDate", Order = 15, TypeName = "datetime")]
        [Required]
        [Display(Name = "Updated date")]
        public System.DateTime UpdatedDate { get; set; }

        public System.Collections.Generic.ICollection<ParticipationActivity> ParticipationActivities { get; set; }
        public System.Collections.Generic.ICollection<ParticipationAnonymousClick> ParticipationAnonymousClicks { get; set; }
        public System.Collections.Generic.ICollection<ParticipationDiscuss> ParticipationDiscusses { get; set; }
        public System.Collections.Generic.ICollection<ParticipationDocument> ParticipationDocuments { get; set; }
        public System.Collections.Generic.ICollection<ParticipationHyperlink> ParticipationHyperlinks { get; set; }
        public System.Collections.Generic.ICollection<ParticipationTag> ParticipationTags { get; set; }
        public System.Collections.Generic.ICollection<Photo> Photos { get; set; }

        public Participation()
        {
            ParticipationId = System.Guid.NewGuid();
            EnableDiscuss = false;
            IsMothball = false;
            IsEnabled = true;
            CreatedBy = "";
            CreatedDate = System.DateTime.Now;
            UpdatedBy = "";
            UpdatedDate = System.DateTime.Now;
            ParticipationActivities = new System.Collections.Generic.List<ParticipationActivity>();
            ParticipationAnonymousClicks = new System.Collections.Generic.List<ParticipationAnonymousClick>();
            ParticipationTags = new System.Collections.Generic.List<ParticipationTag>();
            ParticipationDiscusses = new System.Collections.Generic.List<ParticipationDiscuss>();
            ParticipationDocuments = new System.Collections.Generic.List<ParticipationDocument>();
            ParticipationHyperlinks = new System.Collections.Generic.List<ParticipationHyperlink>();
            Photos = new System.Collections.Generic.List<Photo>();
        }
    }

}
// </auto-generated>
