// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ParticipationDiscussConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ParticipationDiscuss>
    {
        public ParticipationDiscussConfiguration()
            : this("dbo")
        {
        }

        public ParticipationDiscussConfiguration(string schema)
        {
            Property(x => x.UpperId).IsOptional();

            HasMany(t => t.AspNetUsers).WithMany(t => t.ParticipationDiscusses_DiscussId).Map(m =>
            {
                m.ToTable("RelPushParticipationDiscussUser", "dbo");
                m.MapLeftKey("DiscussId");
                m.MapRightKey("Id");
            });
            HasMany(t => t.ParticipationTags).WithMany(t => t.ParticipationDiscusses).Map(m =>
            {
                m.ToTable("RelParticipationDiscussTag", "dbo");
                m.MapLeftKey("DiscussId");
                m.MapRightKey("TagId");
            });
            HasMany(t => t.Participations).WithMany(t => t.ParticipationDiscusses).Map(m =>
            {
                m.ToTable("RelParticipationDiscuss", "dbo");
                m.MapLeftKey("DiscussId");
                m.MapRightKey("ParticipationId");
            });
        }
    }

}
// </auto-generated>
