// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("ParticipationHyperlink", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ParticipationHyperlink
    {

        ///<summary>
        /// 連結網址編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"HyperlinkId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_ParticipationHyperlink", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Hyperlink ID")]
        public System.Guid HyperlinkId { get; set; }

        ///<summary>
        /// 連結名稱
        ///</summary>
        [Column(@"Title", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Title")]
        public string Title { get; set; }

        ///<summary>
        /// 連結說明
        ///</summary>
        [Column(@"Description", Order = 3, TypeName = "nvarchar")]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        ///<summary>
        /// 連結網址
        ///</summary>
        [Column(@"Url", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(200)]
        [StringLength(200)]
        [Url]
        [Display(Name = "Url")]
        public string Url { get; set; }

        ///<summary>
        /// 是否顯示
        ///</summary>
        [Column(@"IsEnabled", Order = 5, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        ///<summary>
        /// 建立人員
        ///</summary>
        [Column(@"CreatedBy", Order = 6, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        ///<summary>
        /// 建立時間
        ///</summary>
        [Column(@"CreatedDate", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        ///<summary>
        /// 修改人員
        ///</summary>
        [Column(@"UpdatedBy", Order = 8, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Updated by")]
        public string UpdatedBy { get; set; }

        ///<summary>
        /// 修改時間
        ///</summary>
        [Column(@"UpdatedDate", Order = 9, TypeName = "datetime")]
        [Required]
        [Display(Name = "Updated date")]
        public System.DateTime UpdatedDate { get; set; }

        public System.Collections.Generic.ICollection<Participation> Participations { get; set; }

        public ParticipationHyperlink()
        {
            HyperlinkId = System.Guid.NewGuid();
            IsEnabled = true;
            CreatedBy = "";
            CreatedDate = System.DateTime.Now;
            UpdatedBy = "";
            UpdatedDate = System.DateTime.Now;
            Participations = new System.Collections.Generic.List<Participation>();
        }
    }

}
// </auto-generated>
