// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ParticipationConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Participation>
    {
        public ParticipationConfiguration()
            : this("dbo")
        {
        }

        public ParticipationConfiguration(string schema)
        {
            Property(x => x.Announcement).IsOptional();
            HasMany(t => t.Photos).WithMany(t => t.Participations).Map(m =>
            {
                m.ToTable("RelParticipationPhoto", "dbo");
                m.MapLeftKey("ParticipationId");
                m.MapRightKey("PHOTO_ID");
            });
        }
    }

}
// </auto-generated>
