// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ParticipationActivityConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ParticipationActivity>
    {
        public ParticipationActivityConfiguration()
            : this("dbo")
        {
        }

        public ParticipationActivityConfiguration(string schema)
        {

            HasMany(t => t.ParticipationDocuments).WithMany(t => t.ParticipationActivities).Map(m =>
            {
                m.ToTable("RelParticipationActivity", "dbo");
                m.MapLeftKey("ActivityId");
                m.MapRightKey("DocumentId");
            });
        }
    }

}
// </auto-generated>
