// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("ParticipationDiscuss", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ParticipationDiscuss
    {

        ///<summary>
        /// 討論區編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"DiscussId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_ParticipationDiscuss", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Discuss ID")]
        public System.Guid DiscussId { get; set; }

        ///<summary>
        /// 市政參與編號
        ///</summary>
        [Column(@"ParticipationId", Order = 2, TypeName = "uniqueidentifier")]
        [Required]
        [Display(Name = "Participation ID")]
        public System.Guid ParticipationId { get; set; }

        ///<summary>
        /// 使用者編號
        ///</summary>
        [Column(@"UserId", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "User ID")]
        public string UserId { get; set; }

        ///<summary>
        /// 上層討論區編號
        ///</summary>
        [Column(@"UpperId", Order = 4, TypeName = "uniqueidentifier")]
        [Display(Name = "Upper ID")]
        public System.Guid? UpperId { get; set; }

        ///<summary>
        /// 討論內容
        ///</summary>
        [Column(@"Message", Order = 5, TypeName = "nvarchar")]
        [Required]
        [MaxLength(4000)]
        [StringLength(4000)]
        [Display(Name = "Message")]
        public string Message { get; set; }

        ///<summary>
        /// 置頂
        ///</summary>
        [Column(@"IsTop", Order = 6, TypeName = "bit")]
        [Required]
        [Display(Name = "Is top")]
        public bool IsTop { get; set; }

        ///<summary>
        /// 是否顯示
        ///</summary>
        [Column(@"IsEnabled", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        ///<summary>
        /// 建立人員
        ///</summary>
        [Column(@"CreatedBy", Order = 8, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        ///<summary>
        /// 建立時間
        ///</summary>
        [Column(@"CreatedDate", Order = 9, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        ///<summary>
        /// 修改人員
        ///</summary>
        [Column(@"UpdatedBy", Order = 10, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Updated by")]
        public string UpdatedBy { get; set; }

        ///<summary>
        /// 修改時間
        ///</summary>
        [Column(@"UpdatedDate", Order = 11, TypeName = "datetime")]
        [Required]
        [Display(Name = "Updated date")]
        public System.DateTime UpdatedDate { get; set; }

        public System.Collections.Generic.ICollection<AspNetUser> AspNetUsers { get; set; }
        public System.Collections.Generic.ICollection<Participation> Participations { get; set; }
        public System.Collections.Generic.ICollection<ParticipationTag> ParticipationTags { get; set; }


        [ForeignKey("UserId")] public AspNetUser AspNetUser { get; set; }

        public ParticipationDiscuss()
        {
            DiscussId = System.Guid.NewGuid();
            IsTop = false;
            IsEnabled = true;
            CreatedBy = "";
            CreatedDate = System.DateTime.Now;
            UpdatedBy = "";
            UpdatedDate = System.DateTime.Now;
            AspNetUsers = new System.Collections.Generic.List<AspNetUser>();
            ParticipationTags = new System.Collections.Generic.List<ParticipationTag>();
            Participations = new System.Collections.Generic.List<Participation>();
        }
    }

}
// </auto-generated>
