// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("ParticipationActivity", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ParticipationActivity
    {

        ///<summary>
        /// 活動編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"ActivityId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_ParticipationActivity", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Activity ID")]
        public System.Guid ActivityId { get; set; }

        ///<summary>
        /// 市政參與編號
        ///</summary>
        [Column(@"ParticipationId", Order = 2, TypeName = "uniqueidentifier")]
        [Required]
        [Display(Name = "Participation ID")]
        public System.Guid ParticipationId { get; set; }

        ///<summary>
        /// 主題
        ///</summary>
        [Column(@"Subject", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(300)]
        [StringLength(300)]
        [Display(Name = "Subject")]
        public string Subject { get; set; }

        ///<summary>
        /// 描述
        ///</summary>
        [Column(@"Description", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(2000)]
        [StringLength(2000)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        ///<summary>
        /// 日期與時間
        ///</summary>
        [Column(@"HoldDate", Order = 5, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Hold date")]
        public string HoldDate { get; set; }

        ///<summary>
        /// 地點
        ///</summary>
        [Column(@"Location", Order = 6, TypeName = "nvarchar")]
        [Required]
        [MaxLength(200)]
        [StringLength(200)]
        [Display(Name = "Location")]
        public string Location { get; set; }

        ///<summary>
        /// 0: 論壇活動, 1: 工作坊
        ///</summary>
        [Column(@"ActivityType", Order = 7, TypeName = "int")]
        [Required]
        [Display(Name = "Activity type")]
        public int ActivityType { get; set; }

        ///<summary>
        /// 是否顯示
        ///</summary>
        [Column(@"IsEnabled", Order = 8, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        ///<summary>
        /// 建立人員
        ///</summary>
        [Column(@"CreatedBy", Order = 9, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        ///<summary>
        /// 建立時間
        ///</summary>
        [Column(@"CreatedDate", Order = 10, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        ///<summary>
        /// 修改人員
        ///</summary>
        [Column(@"UpdatedBy", Order = 11, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "Updated by")]
        public string UpdatedBy { get; set; }

        ///<summary>
        /// 修改時間
        ///</summary>
        [Column(@"UpdatedDate", Order = 12, TypeName = "datetime")]
        [Required]
        [Display(Name = "Updated date")]
        public System.DateTime UpdatedDate { get; set; }

        public System.Collections.Generic.ICollection<ParticipationDocument> ParticipationDocuments { get; set; }


        [ForeignKey("ParticipationId")] public Participation Participation { get; set; }

        public ParticipationActivity()
        {
            ActivityId = System.Guid.NewGuid();
            ActivityType = 0;
            IsEnabled = true;
            CreatedBy = "";
            CreatedDate = System.DateTime.Now;
            UpdatedBy = "";
            UpdatedDate = System.DateTime.Now;
            ParticipationDocuments = new System.Collections.Generic.List<ParticipationDocument>();
        }
    }

}
// </auto-generated>
