// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("PHOTO_EXT", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class PhotoExt
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"PHOTO_ID", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.PHOTO_EXT", 1, IsUnique = true, IsClustered = true)]
        [Index(@"IX_PHOTO_ID", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Key]
        [Display(Name = "Photo ID")]
        [ForeignKey("Photo")]
        public System.Guid PhotoId { get; set; }

        [Column(@"ORIGINAL", Order = 2, TypeName = "image")]
        [Required]
        [MaxLength(2147483647)]
        [Display(Name = "Original")]
        public byte[] Original { get; set; }

        [Column(@"WIDTH1024", Order = 3, TypeName = "image")]
        [Required]
        [MaxLength(2147483647)]
        [Display(Name = "Width 1024")]
        public byte[] Width1024 { get; set; }

        [Column(@"WIDTH768", Order = 4, TypeName = "image")]
        [Required]
        [MaxLength(2147483647)]
        [Display(Name = "Width 768")]
        public byte[] Width768 { get; set; }

        [Column(@"WIDTH320", Order = 5, TypeName = "image")]
        [Required]
        [MaxLength(2147483647)]
        [Display(Name = "Width 320")]
        public byte[] Width320 { get; set; }

        [Column(@"WIDTH120", Order = 6, TypeName = "image")]
        [Required]
        [MaxLength(2147483647)]
        [Display(Name = "Width 120")]
        public byte[] Width120 { get; set; }


        [ForeignKey("PhotoId")] public Photo Photo { get; set; }
    }

}
// </auto-generated>
