// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class ShowCaseConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ShowCase>
    {
        public ShowCaseConfiguration()
            : this("dbo")
        {
        }

        public ShowCaseConfiguration(string schema)
        {
            HasMany(t => t.DataSets).WithMany(t => t.ShowCases).Map(m =>
            {
                m.ToTable("ShowCaseRelDataSet", "dbo");
                m.MapLeftKey("CaseId");
                m.MapRightKey("SetId");
            });
            HasMany(t => t.Photos).WithMany(t => t.ShowCases).Map(m =>
            {
                m.ToTable("ShowCaseRelPhoto", "dbo");
                m.MapLeftKey("CaseId");
                m.MapRightKey("PhotoId");
            });
        }
    }

}
// </auto-generated>
