// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("TAG", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class Tag
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"TAG_ID", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.TAG", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Tag ID")]
        public System.Guid TagId { get; set; }

        [Column(@"TAG_NAME", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Tag name")]
        public string TagName { get; set; }

        [Column(@"IS_ENABLED", Order = 3, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        [Column(@"CREATED_BY", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        [Column(@"CREATED_DATE", Order = 5, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        [Column(@"UPDATE_BY", Order = 6, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Update by")]
        public string UpdateBy { get; set; }

        [Column(@"UPDATE_DATE", Order = 7, TypeName = "datetime")]
        [Required]
        [Display(Name = "Update date")]
        public System.DateTime UpdateDate { get; set; }

        [Column(@"FORUM_ID", Order = 8, TypeName = "uniqueidentifier")]
        [Index(@"IX_FORUM_ID", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Forum ID")]
        public System.Guid ForumId { get; set; }

        [Column(@"SORT", Order = 9, TypeName = "int")]
        [Required]
        [Display(Name = "Sort")]
        public int Sort { get; set; }

        public System.Collections.Generic.ICollection<Discuss> Discusses { get; set; }


        [ForeignKey("ForumId")] public Forum Forum { get; set; }

        public Tag()
        {
            ForumId = System.Guid.Parse("9258dbf9-80ec-e411-82d7-bcee7bd92c28");
            Sort = 0;
            Discusses = new System.Collections.Generic.List<Discuss>();
        }
    }

}
// </auto-generated>
