// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("VoteBasic", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class VoteBasic
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"BasicId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.VoteBasic", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Basic ID")]
        public System.Guid BasicId { get; set; }

        ///<summary>
        /// 個資分類編號
        ///</summary>
        [Column(@"GroupId", Order = 2, TypeName = "int")]
        [Index(@"IX_GroupId", 1, IsUnique = false, IsClustered = false)]
        [Required]
        [Display(Name = "Group ID")]
        public int GroupId { get; set; }

        ///<summary>
        /// 標題
        ///</summary>
        [Column(@"Name", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        ///<summary>
        /// 排序
        ///</summary>
        [Column(@"Sort", Order = 4, TypeName = "int")]
        [Required]
        [Display(Name = "Sort")]
        public int Sort { get; set; }

        ///<summary>
        /// 是否顯示
        ///</summary>
        [Column(@"IsEnabled", Order = 5, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        ///<summary>
        /// 建立時間
        ///</summary>
        [Column(@"CreatedDate", Order = 6, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        ///<summary>
        /// 是否需填寫內容
        ///</summary>
        [Column(@"IsExplain", Order = 7, TypeName = "bit")]
        [Required]
        [Display(Name = "Is explain")]
        public bool IsExplain { get; set; }


        [ForeignKey("GroupId")] public VoteBasicGroup VoteBasicGroup { get; set; }

        public VoteBasic()
        {
            BasicId = System.Guid.NewGuid();
            Name = "";
            Sort = 0;
            IsEnabled = true;
            CreatedDate = System.DateTime.Now;
            IsExplain = false;
        }
    }

}
// </auto-generated>
