// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("VoteCheck", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class VoteCheck
    {

        ///<summary>
        /// 投票編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"VoteId", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.VoteCheck", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Vote ID")]
        public System.Guid VoteId { get; set; }

        ///<summary>
        /// userMail
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"UserEmail", Order = 2, TypeName = "nvarchar")]
        [Index(@"PK_dbo.VoteCheck", 2, IsUnique = true, IsClustered = true)]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Key]
        [Display(Name = "User email")]
        public string UserEmail { get; set; }

        ///<summary>
        /// 匿名ID
        ///</summary>
        [Column(@"UserId", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Display(Name = "User ID")]
        public string UserId { get; set; }

        ///<summary>
        /// 是否有效
        ///</summary>
        [Column(@"IsEnabled", Order = 4, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        ///<summary>
        /// 建立時間
        ///</summary>
        [Column(@"CreatedDate", Order = 5, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        public VoteCheck()
        {
            UserEmail = "";
            UserId = "";
            IsEnabled = false;
            CreatedDate = System.DateTime.Now;
        }
    }

}
// </auto-generated>
