// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("VoteFillBasic", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class VoteFillBasic
    {

        ///<summary>
        /// 投票人
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"UserId", Order = 1, TypeName = "nvarchar")]
        [Index(@"PK_dbo.VoteFillBasic", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [MaxLength(128)]
        [StringLength(128)]
        [Key]
        [Display(Name = "User ID")]
        public string UserId { get; set; }

        ///<summary>
        /// 個資編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"BasicId", Order = 2, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.VoteFillBasic", 2, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Basic ID")]
        public System.Guid BasicId { get; set; }

        ///<summary>
        /// 投票編號
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"VoteId", Order = 3, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.VoteFillBasic", 3, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Vote ID")]
        public System.Guid VoteId { get; set; }

        ///<summary>
        /// 填寫內容
        ///</summary>
        [Column(@"BasicDesc", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(500)]
        [StringLength(500)]
        [Display(Name = "Basic desc")]
        public string BasicDesc { get; set; }

        ///<summary>
        /// 個資分類編號
        ///</summary>
        [Column(@"GroupId", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Group ID")]
        public int GroupId { get; set; }

        ///<summary>
        /// 投票時間
        ///</summary>
        [Column(@"CreatedDate", Order = 6, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        public VoteFillBasic()
        {
            BasicDesc = "";
            CreatedDate = System.DateTime.Now;
        }
    }

}
// </auto-generated>
