// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("WaitingMail", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class WaitingMail
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"MailSeq", Order = 1, TypeName = "int")]
        [Index(@"PK_dbo.WaitingMail", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Mail seq")]
        public int MailSeq { get; set; }

        ///<summary>
        /// 寄發系統
        ///</summary>
        [Column(@"TypeName", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(400)]
        [StringLength(400)]
        [Display(Name = "Type name")]
        public string TypeName { get; set; }

        ///<summary>
        /// 收件人姓名
        ///</summary>
        [Column(@"ToName", Order = 3, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "To name")]
        public string ToName { get; set; }

        ///<summary>
        /// 收件人Email
        ///</summary>
        [Column(@"ToEmail", Order = 4, TypeName = "nvarchar")]
        [Required]
        [MaxLength(400)]
        [StringLength(400)]
        [Display(Name = "To email")]
        public string ToEmail { get; set; }

        ///<summary>
        /// 寄件人姓名
        ///</summary>
        [Column(@"FromName", Order = 5, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "From name")]
        public string FromName { get; set; }

        ///<summary>
        /// 寄件人Email
        ///</summary>
        [Column(@"FromEmail", Order = 6, TypeName = "nvarchar")]
        [Required]
        [MaxLength(400)]
        [StringLength(400)]
        [Display(Name = "From email")]
        public string FromEmail { get; set; }

        ///<summary>
        /// 密件Email
        ///</summary>
        [Column(@"BccEmail", Order = 7, TypeName = "nvarchar")]
        [Required]
        [MaxLength(800)]
        [StringLength(800)]
        [Display(Name = "Bcc email")]
        public string BccEmail { get; set; }

        ///<summary>
        /// 郵件主旨
        ///</summary>
        [Column(@"Subject", Order = 8, TypeName = "nvarchar")]
        [Required]
        [MaxLength(256)]
        [StringLength(256)]
        [Display(Name = "Subject")]
        public string Subject { get; set; }

        ///<summary>
        /// 郵件內容
        ///</summary>
        [Column(@"MailContent", Order = 9, TypeName = "nvarchar(max)")]
        [Required]
        [Display(Name = "Mail content")]
        public string MailContent { get; set; }

        ///<summary>
        /// 是否已發送
        ///</summary>
        [Column(@"IsSend", Order = 10, TypeName = "bit")]
        [Required]
        [Display(Name = "Is send")]
        public bool IsSend { get; set; }

        ///<summary>
        /// 新增日期
        ///</summary>
        [Column(@"CreateTime", Order = 11, TypeName = "datetime")]
        [Required]
        [Display(Name = "Create time")]
        public System.DateTime CreateTime { get; set; }

        ///<summary>
        /// 實際發送日期
        ///</summary>
        [Column(@"SendTime", Order = 12, TypeName = "datetime")]
        [Display(Name = "Send time")]
        public System.DateTime? SendTime { get; set; }

        public WaitingMail()
        {
            TypeName = "";
            ToName = "";
            ToEmail = "";
            FromName = "";
            FromEmail = "";
            BccEmail = "";
            Subject = "";
            MailContent = "";
            IsSend = false;
            CreateTime = System.DateTime.Now;
        }
    }

}
// </auto-generated>
