// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Geo.Grid.Tainan.OpenGov.DbModel.CodeFirst
{

    [Table("YOUTUBE", Schema = "dbo")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
    public class Youtube
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(@"YOUTUBE_ID", Order = 1, TypeName = "uniqueidentifier")]
        [Index(@"PK_dbo.YOUTUBE", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Youtube ID")]
        public System.Guid YoutubeId { get; set; }

        [Column(@"NAME", Order = 2, TypeName = "nvarchar")]
        [Required]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Name")]
        public string Name { get; set; }

        [Column(@"URL", Order = 3, TypeName = "nvarchar")]
        [MaxLength(4000)]
        [StringLength(4000)]
        [Url]
        [Display(Name = "Url")]
        public string Url { get; set; }

        [Column(@"START_DATE", Order = 4, TypeName = "datetime")]
        [Required]
        [Display(Name = "Start date")]
        public System.DateTime StartDate { get; set; }

        [Column(@"VIDEO_TIME", Order = 5, TypeName = "nvarchar")]
        [MaxLength(50)]
        [StringLength(50)]
        [Display(Name = "Video time")]
        public string VideoTime { get; set; }

        [Column(@"IS_OPENED", Order = 6, TypeName = "bit")]
        [Required]
        [Display(Name = "Is opened")]
        public bool IsOpened { get; set; }

        [Column(@"DESCRIPTION", Order = 7, TypeName = "nvarchar")]
        [MaxLength(4000)]
        [StringLength(4000)]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Column(@"END_DATE", Order = 8, TypeName = "datetime")]
        [Required]
        [Display(Name = "End date")]
        public System.DateTime EndDate { get; set; }

        [Column(@"IS_ENABLED", Order = 9, TypeName = "bit")]
        [Required]
        [Display(Name = "Is enabled")]
        public bool IsEnabled { get; set; }

        [Column(@"CREATED_BY", Order = 10, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Created by")]
        public string CreatedBy { get; set; }

        [Column(@"CREATED_DATE", Order = 11, TypeName = "datetime")]
        [Required]
        [Display(Name = "Created date")]
        public System.DateTime CreatedDate { get; set; }

        [Column(@"UPDATE_BY", Order = 12, TypeName = "nvarchar")]
        [Required]
        [MaxLength(100)]
        [StringLength(100)]
        [Display(Name = "Update by")]
        public string UpdateBy { get; set; }

        [Column(@"UPDATE_DATE", Order = 13, TypeName = "datetime")]
        [Required]
        [Display(Name = "Update date")]
        public System.DateTime UpdateDate { get; set; }

        public Youtube()
        {
            YoutubeId = System.Guid.NewGuid();
        }
    }

}
// </auto-generated>
