CREATE TABLE [dbo].[DOCUMENT_EXT] (
    [DOCUMENT_ID] UNIQUEIDENTIFIER NOT NULL,
    [ORIGINAL]    VARBINARY (MAX)  NOT NULL,
    CONSTRAINT [PK_dbo.DOCUMENT_EXT] PRIMARY KEY CLUSTERED ([DOCUMENT_ID] ASC),
    CONSTRAINT [FK_dbo.DOCUMENT_EXT_dbo.DOCUMENT_DOCUMENT_ID] FOREIGN KEY ([DOCUMENT_ID]) REFERENCES [dbo].[DOCUMENT] ([DOCUMENT_ID]) ON DELETE CASCADE
);




GO



GO
CREATE NONCLUSTERED INDEX [IX_DOCUMENT_ID]
    ON [dbo].[DOCUMENT_EXT]([DOCUMENT_ID] ASC);

