CREATE TABLE [dbo].[HYPERLINK] (
    [HYPERLINK_ID] UNIQUEIDENTIFIER DEFAULT (newsequentialid()) NOT NULL,
    [TITLE]        NVARCHAR (200)   NOT NULL,
    [DESCRIPTION]  NVARCHAR (500)   NULL,
    [URL]          NVARCHAR (200)   NOT NULL,
    [IS_ENABLED]   BIT              NOT NULL,
    [CREATED_BY]   NVARCHAR (100)   NOT NULL,
    [CREATED_DATE] DATETIME         NOT NULL,
    [UPDATE_BY]    NVARCHAR (100)   NOT NULL,
    [UPDATE_DATE]  DATETIME         NOT NULL,
    CONSTRAINT [PK_dbo.HYPERLINK] PRIMARY KEY CLUSTERED ([HYPERLINK_ID] ASC)
);




GO



GO



GO



GO



GO



GO


