CREATE TABLE [dbo].[PHOTO_EXT] (
    [PHOTO_ID]  UNIQUEIDENTIFIER NOT NULL,
    [ORIGINAL]  IMAGE            NOT NULL,
    [WIDTH1024] IMAGE            NOT NULL,
    [WIDTH768]  IMAGE            NOT NULL,
    [WIDTH320]  IMAGE            NOT NULL,
    [WIDTH120]  IMAGE            NOT NULL,
    CONSTRAINT [PK_dbo.PHOTO_EXT] PRIMARY KEY CLUSTERED ([PHOTO_ID] ASC),
    CONSTRAINT [FK_dbo.PHOTO_EXT_dbo.PHOTO_PHOTO_ID] FOREIGN KEY ([PHOTO_ID]) REFERENCES [dbo].[PHOTO] ([PHOTO_ID]) ON DELETE CASCADE
);




GO



GO



GO



GO



GO



GO
CREATE NONCLUSTERED INDEX [IX_PHOTO_ID]
    ON [dbo].[PHOTO_EXT]([PHOTO_ID] ASC);

