CREATE TABLE [dbo].[REL_DISCUSS_TAG] (
    [DiscussId] UNIQUEIDENTIFIER NOT NULL,
    [TagId]     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_dbo.REL_DISCUSS_TAG] PRIMARY KEY CLUSTERED ([DiscussId] ASC, [TagId] ASC),
    CONSTRAINT [FK_dbo.REL_DISCUSS_TAG_dbo.DISCUSS_DiscussId] FOREIGN KEY ([DiscussId]) REFERENCES [dbo].[DISCUSS] ([DISCUSS_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dbo.REL_DISCUSS_TAG_dbo.TAG_TagId] FOREIGN KEY ([TagId]) REFERENCES [dbo].[TAG] ([TAG_ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_TagId]
    ON [dbo].[REL_DISCUSS_TAG]([TagId] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DiscussId]
    ON [dbo].[REL_DISCUSS_TAG]([DiscussId] ASC);

