CREATE TABLE [dbo].[REL_USER_PUSH] (
    [DiscussId] UNIQUEIDENTIFIER NOT NULL,
    [Id]        NVARCHAR (128)   NOT NULL,
    CONSTRAINT [PK_dbo.REL_USER_PUSH] PRIMARY KEY CLUSTERED ([DiscussId] ASC, [Id] ASC),
    CONSTRAINT [FK_dbo.REL_USER_PUSH_dbo.AspNetUsers_Id] FOREIGN KEY ([Id]) REFERENCES [dbo].[AspNetUsers] ([Id]) ON DELETE CASCADE,
    CONSTRAINT [FK_dbo.REL_USER_PUSH_dbo.DISCUSS_DiscussId] FOREIGN KEY ([DiscussId]) REFERENCES [dbo].[DISCUSS] ([DISCUSS_ID]) ON DELETE CASCADE
);


GO
CREATE NONCLUSTERED INDEX [IX_Id]
    ON [dbo].[REL_USER_PUSH]([Id] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DiscussId]
    ON [dbo].[REL_USER_PUSH]([DiscussId] ASC);

