CREATE TABLE [dbo].[REL_FORUM_DOCUMENT] (
    [DOCUMENT_ID] UNIQUEIDENTIFIER NOT NULL,
    [FORUM_ID]    UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_dbo.REL_FORUM_DOCUMENT] PRIMARY KEY CLUSTERED ([DOCUMENT_ID] ASC, [FORUM_ID] ASC),
    CONSTRAINT [FK_dbo.REL_FORUM_DOCUMENT_dbo.DOCUMENT_DOCUMENT_ID] FOREIGN KEY ([DOCUMENT_ID]) REFERENCES [dbo].[DOCUMENT] ([DOCUMENT_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dbo.REL_FORUM_DOCUMENT_dbo.FORUM_FORUM_ID] FOREIGN KEY ([FORUM_ID]) REFERENCES [dbo].[FORUM] ([FORUM_ID]) ON DELETE CASCADE
);




GO



GO
CREATE NONCLUSTERED INDEX [IX_FORUM_ID]
    ON [dbo].[REL_FORUM_DOCUMENT]([FORUM_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_DOCUMENT_ID]
    ON [dbo].[REL_FORUM_DOCUMENT]([DOCUMENT_ID] ASC);

