CREATE TABLE [dbo].[REL_ACTIVITY_DOCUMENT] (
    [ACTIVITY_ID] UNIQUEIDENTIFIER NOT NULL,
    [DOCUMENT_ID] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_dbo.REL_ACTIVITY_DOCUMENT] PRIMARY KEY CLUSTERED ([ACTIVITY_ID] ASC, [DOCUMENT_ID] ASC),
    CONSTRAINT [FK_dbo.REL_ACTIVITY_DOCUMENT_dbo.ACTIVITY_ACTIVITY_ID] FOREIGN KEY ([ACTIVITY_ID]) REFERENCES [dbo].[ACTIVITY] ([ACTIVITY_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_dbo.REL_ACTIVITY_DOCUMENT_dbo.DOCUMENT_DOCUMENT_ID] FOREIGN KEY ([DOCUMENT_ID]) REFERENCES [dbo].[DOCUMENT] ([DOCUMENT_ID]) ON DELETE CASCADE
);




GO
CREATE NONCLUSTERED INDEX [IX_DOCUMENT_ID]
    ON [dbo].[REL_ACTIVITY_DOCUMENT]([DOCUMENT_ID] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_ACTIVITY_ID]
    ON [dbo].[REL_ACTIVITY_DOCUMENT]([ACTIVITY_ID] ASC);

