CREATE TABLE [dbo].[TAG] (
    [TAG_ID]       UNIQUEIDENTIFIER NOT NULL,
    [TAG_NAME]     NVARCHAR (50)    NOT NULL,
    [IS_ENABLED]   BIT              NOT NULL,
    [CREATED_BY]   NVARCHAR (100)   NOT NULL,
    [CREATED_DATE] DATETIME         NOT NULL,
    [UPDATE_BY]    NVARCHAR (100)   NOT NULL,
    [UPDATE_DATE]  DATETIME         NOT NULL,
    [FORUM_ID]     UNIQUEIDENTIFIER DEFAULT ('9258dbf9-80ec-e411-82d7-bcee7bd92c28') NOT NULL,
    [SORT]         INT              DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_dbo.TAG] PRIMARY KEY CLUSTERED ([TAG_ID] ASC),
    CONSTRAINT [FK_dbo.TAG_dbo.FORUM_FORUM_ID] FOREIGN KEY ([FORUM_ID]) REFERENCES [dbo].[FORUM] ([FORUM_ID])
);




GO
CREATE NONCLUSTERED INDEX [IX_FORUM_ID]
    ON [dbo].[TAG]([FORUM_ID] ASC);

